### ISSUE TITLE
最新版7.10是不是没效果啊？？

### ISSUE THREAD

**Issue by AwcySama** [4ch12dy/fkwechatzan#13]
试了很久，都没有能集到赞

**Comment by 4ch12dy** [comment]
姿势没对吧，可以正常使用

**Comment by Catnipll** [comment]
大佬，为什么我用最初版本v0.0.2反而有效，用最新版完全没效果，朋友圈首页刷新了，进到自己朋友圈打开也没有，反而是最初版一刷新必出😂

**Comment by Catnipll** [comment]
> 姿势没对吧，可以正常使用

大佬，为什么我用最初版本v0.0.2反而有效，用最新版完全没效果，朋友圈首页刷新了，进到自己朋友圈打开也没有，反而是最初版v0.0.2一刷新必出😂11pm iOS13.5

**Comment by 4ch12dy** [comment]
有时候网络问题，如果没有就给自己点个赞就有了。另外有些设置开关没弄对也会出现这个问题
