### ISSUE TITLE
不会被封号吗

### ISSUE THREAD

**Issue by Aix6** [4ch12dy/fkwechatzan#2]
感觉现在微信都不能动了，一动就封号！请问你们是怎么绕过微信检测的，还是越狱手机装插件的方式不影响？

**Comment by 4ch12dy** [comment]
关于封号的问题，请自行斟酌。一般来说非白号，小号，自己正常使用的号封的概率很小。

**Comment by Aix6** [comment]
设置了后怎么触发啊？怎么感觉设置了没用，还是我不会用。。。

**Comment by 4ch12dy** [comment]
发一条朋友圈，或者去自己朋友圈里面看就应该能看到增加的赞和评论

**Comment by Aix6** [comment]
是不是微信版本有要求？我用 7.0+ 按三种方式装了都不起作用，能设置，但发圈后没自动点赞评论

**Comment by 4ch12dy** [comment]
微信7.0以上就行，刷新一下朋友圈，或者去自己朋友圈应该就有了

**Comment by Aix6** [comment]
可以了，好像有 bug，点进详情再出来才会有

**Comment by Aix6** [comment]
好友是随机的？我用个小号测试，都没好友，点进详情可以刷出一堆不认识的人

**Comment by 4ch12dy** [comment]
是的，随机选择的。后面有准备开发选择指定好友，以及其他功能。保持关注（其实是暂时没时间开发

**Comment by Aix6** [comment]
哈哈。不过我奇怪的是有些好像都不是我好友，有些是群组，还有“微信运动”这种官方的点赞

**Comment by 4ch12dy** [comment]
嗯，群里面的人也有。准确地说是你的联系人，并不一定是你好友。这个后面也会设置个开关选择

**Comment by Aix6** [comment]
明白了，谢谢
