### ISSUE TITLE
微信最新版7.0.15，点击设置卡死问题

### ISSUE THREAD

**Issue by Catnipll** [4ch12dy/fkwechatzan#20]
大佬您好，目前使用的是您源内：
【微信积赞助手xia0Dev版0.1-1】（兼容了新旧版本的微信，修复了众多bug，优化了速度和稳定性。）

在升级了微信最新版7.0.15之后，点击积攒助手的设置选项，会直接卡死。听说7.0.15版微信对函数做了一些改动，不知道大佬是否有同步更新积赞助手，适配最新版微信的计划？🙏🏻🙏🏻麻烦大佬啦，感恩感谢大佬🙏🏻🙏🏻🙏🏻￼

**Comment by Catnipll** [comment]
昨天晚上Issues了一次，结果不见了😂今早再Issues一次，终于正常了没被吞🤣🤣🤣

**Comment by 4ch12dy** [comment]
7.0.15版本微信界面api改动了，得适配下，关注源就行，源里会尽快适配最新版本

**Comment by Catnipll** [comment]
> 7.0.15版本微信界面api改动了，得适配下，关注源就行，源里会尽快适配最新版本

好的好的，感恩感恩，感谢大佬🙏🏻

**Comment by 4ch12dy** [comment]
已经修复了7.0.15闪退问题
